-- Generated by Mocodo 4.0.2

CREATE TABLE CANDIDAT (
  AUTO_INCREMENT PRIMARY KEY (candidate_id),
  candidate_id VARCHAR(42) NOT NULL AUTO_INCREMENT,
  candidate_first_name VARCHAR(42),
  candidate_last_name VARCHAR(42),
  candidate_sex VARCHAR(6),
  candidate_email VARCHAR(255),
  candidate_phone_number VARCHAR(12),
  candidate_localisation VARCHAR(255),
  candidate_about MEDIUMTEXT,
  candidate_profile_picture VARCHAR(255),
  candidate_cover_picture VARCHAR(255),
  candidate_status VARCHAR(255)
);

CREATE TABLE CERTIFICATION (
  AUTO_INCREMENT PRIMARY KEY (certification_name),
  certification_name VARCHAR(42) NOT NULL,
  certification_icon VARCHAR(42)
);

CREATE TABLE COMPETENCE (
  AUTO_INCREMENT PRIMARY KEY (competence_name),
  competence_name VARCHAR(42) NOT NULL,
  competence_icon VARCHAR(255)
);

CREATE TABLE DEGREE (
  AUTO_INCREMENT PRIMARY KEY (degree_id),
  degree_id VARCHAR(42) NOT NULL,
  degree_name VARCHAR(42),
  degree_school VARCHAR(42),
  degree_start_date DATE,
  degree_end_date DATE,
  candidate_id VARCHAR(42) NOT NULL
);

CREATE TABLE ENTREPRISE (
  AUTO_INCREMENT PRIMARY KEY (entreprise_id),
  entreprise_id VARCHAR(42) NOT NULL,
  entreprise_name VARCHAR(42),
  entreprise_field VARCHAR(255),
  entreprise_about MEDIUMTEXT,
  entreprise_number_of_workers INT,
  entreprise_date_of_creation DATE,
  entreprise_localisation VARCHAR(255),
  entreprise_desired_profiles MEDIUMTEXT,
  entreprise_average_age INT,
  entreprise_profile_picture VARCHAR(255),
  entreprise_cover_picture VARCHAR(255)
);

CREATE TABLE HOBBY (
  AUTO_INCREMENT PRIMARY KEY (hobby_name),
  hobby_name VARCHAR(42) NOT NULL,
  hobby_about MEDIUMTEXT
);

CREATE TABLE Has_Applied (
  AUTO_INCREMENT PRIMARY KEY (candidate_id, offer_id),
  candidate_id VARCHAR(42) NOT NULL,
  offer_id VARCHAR(42) NOT NULL
);

CREATE TABLE Has_Certification (
  AUTO_INCREMENT PRIMARY KEY (candidate_id, certification_name),
  candidate_id VARCHAR(42) NOT NULL,
  certification_name VARCHAR(42) NOT NULL
);

CREATE TABLE Has_Faved (
  AUTO_INCREMENT PRIMARY KEY (candidate_id, offer_id),
  candidate_id VARCHAR(42) NOT NULL,
  offer_id VARCHAR(42) NOT NULL
);

CREATE TABLE Has_hobby (
  AUTO_INCREMENT PRIMARY KEY (candidate_id, hobby_name),
  candidate_id VARCHAR(42) NOT NULL,
  hobby_name VARCHAR(42) NOT NULL
);

CREATE TABLE JOB_OFFER (
  AUTO_INCREMENT PRIMARY KEY (offer_id),
  offer_id VARCHAR(42) NOT NULL,
  offer_title VARCHAR(255),
  offer_contract_length VARCHAR(42),
  offer_publication_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  offer_about MEDIUMTEXT,
  offer_expected_work MEDIUMTEXT,
  offer_annual_salary INT,
  offer_studies_requirement VARCHAR(42),
  entreprise_id VARCHAR(42) NOT NULL
);

CREATE TABLE LANGUAGE (
  AUTO_INCREMENT PRIMARY KEY (language_name),
  language_name VARCHAR(42) NOT NULL,
  language_level VARCHAR(42)
);

CREATE TABLE PROFESSIONNAL_EXPERIENCE (
  AUTO_INCREMENT PRIMARY KEY (experience_id),
  experience_id VARCHAR(42) NOT NULL,
  experience_start_date DATE,
  experience_end_date DATE,
  experience_job_title VARCHAR(42),
  experience_description MEDIUMTEXT,
  candidate_id VARCHAR(42) NOT NULL,
  entreprise_id VARCHAR(42) NOT NULL
);

CREATE TABLE Speaks_language (
  AUTO_INCREMENT PRIMARY KEY (candidate_id, language_name),
  candidate_id VARCHAR(42) NOT NULL,
  language_name VARCHAR(42) NOT NULL
);

CREATE TABLE TOOL (
  AUTO_INCREMENT PRIMARY KEY (tool_name),
  tool_name VARCHAR(42) NOT NULL,
  tool_icon VARCHAR(42)
);

CREATE TABLE Used_Skill (
  AUTO_INCREMENT PRIMARY KEY (experience_id, competence_name),
  experience_id VARCHAR(42) NOT NULL,
  competence_name VARCHAR(42) NOT NULL
);

CREATE TABLE Used_Tool (
  AUTO_INCREMENT PRIMARY KEY (experience_id, tool_name),
  experience_id VARCHAR(42) NOT NULL,
  tool_name VARCHAR(42) NOT NULL
);

ALTER TABLE DEGREE ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE Has_Applied ADD FOREIGN KEY (offer_id) REFERENCES JOB_OFFER (offer_id);
ALTER TABLE Has_Applied ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE Has_Certification ADD FOREIGN KEY (certification_name) REFERENCES CERTIFICATION (certification_name);
ALTER TABLE Has_Certification ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE Has_Faved ADD FOREIGN KEY (offer_id) REFERENCES JOB_OFFER (offer_id);
ALTER TABLE Has_Faved ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE Has_hobby ADD FOREIGN KEY (hobby_name) REFERENCES HOBBY (hobby_name);
ALTER TABLE Has_hobby ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE JOB_OFFER ADD FOREIGN KEY (entreprise_id) REFERENCES ENTREPRISE (entreprise_id);

ALTER TABLE PROFESSIONNAL_EXPERIENCE ADD FOREIGN KEY (entreprise_id) REFERENCES ENTREPRISE (entreprise_id);
ALTER TABLE PROFESSIONNAL_EXPERIENCE ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE Speaks_language ADD FOREIGN KEY (language_name) REFERENCES LANGUAGE (language_name);
ALTER TABLE Speaks_language ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE Used_Skill ADD FOREIGN KEY (competence_name) REFERENCES COMPETENCE (competence_name);
ALTER TABLE Used_Skill ADD FOREIGN KEY (experience_id) REFERENCES PROFESSIONNAL_EXPERIENCE (experience_id);

ALTER TABLE Used_Tool ADD FOREIGN KEY (tool_name) REFERENCES TOOL (tool_name);
ALTER TABLE Used_Tool ADD FOREIGN KEY (experience_id) REFERENCES PROFESSIONNAL_EXPERIENCE (experience_id);
