-- Generated by Mocodo 4.0.2

CREATE TABLE CANDIDAT (
  PRIMARY KEY (candidate_id),
  candidate_id VARCHAR(42) NOT NULL,
  candidate_first_name VARCHAR(42),
  candidate_last_name VARCHAR(42),
  candidate_sex VARCHAR(42),
  candidate_email VARCHAR(42),
  candidate_phone_number VARCHAR(42),
  candidate_localisation VARCHAR(42),
  candidate_about VARCHAR(42),
  candidate_profile_picture VARCHAR(42),
  candidate_cover_picture VARCHAR(42),
  candidate_status VARCHAR(42)
);

CREATE TABLE CERTIFICATION (
  PRIMARY KEY (certification_name),
  certification_name VARCHAR(42) NOT NULL,
  certification_icon VARCHAR(42)
);

CREATE TABLE COMPETENCE (
  PRIMARY KEY (competence_name),
  competence_name VARCHAR(42) NOT NULL,
  competence_icon VARCHAR(42)
);

CREATE TABLE DEGREE (
  PRIMARY KEY (degree_id),
  degree_id VARCHAR(42) NOT NULL,
  degree_name VARCHAR(42),
  degree_school VARCHAR(42),
  degree_start_date VARCHAR(42),
  degree_end_date VARCHAR(42),
  candidate_id VARCHAR(42) NOT NULL
);

CREATE TABLE ENTREPRISE (
  PRIMARY KEY (entreprise_id),
  entreprise_id VARCHAR(42) NOT NULL,
  entreprise_name VARCHAR(42),
  entreprise_field VARCHAR(42),
  entreprise_about VARCHAR(42),
  entreprise_number_of_workers VARCHAR(42),
  entreprise_date_of_creation VARCHAR(42),
  entreprise_localisation VARCHAR(42),
  entreprise_desired_profiles VARCHAR(42),
  entreprise_average_age VARCHAR(42),
  entreprise_profile_picture VARCHAR(42),
  entreprise_cover_picture VARCHAR(42)
);

CREATE TABLE Has_Applied (
  PRIMARY KEY (candidate_id, offer_id),
  candidate_id VARCHAR(42) NOT NULL,
  offer_id VARCHAR(42) NOT NULL
);

CREATE TABLE Has_Certification (
  PRIMARY KEY (candidate_id, certification_name),
  candidate_id VARCHAR(42) NOT NULL,
  certification_name VARCHAR(42) NOT NULL
);

CREATE TABLE Has_Faved (
  PRIMARY KEY (candidate_id, offer_id),
  candidate_id VARCHAR(42) NOT NULL,
  offer_id VARCHAR(42) NOT NULL
);

CREATE TABLE JOB_OFFER (
  PRIMARY KEY (offer_id),
  offer_id VARCHAR(42) NOT NULL,
  offer_title VARCHAR(42),
  offer_contract_length VARCHAR(42),
  offer_publication_date VARCHAR(42),
  offer_about VARCHAR(42),
  offer_expected_work VARCHAR(42),
  offer_annual_salary VARCHAR(42),
  offer_studies_requirement VARCHAR(42),
  entreprise_id VARCHAR(42) NOT NULL
);

CREATE TABLE PROFESSIONNAL_EXPERIENCE (
  PRIMARY KEY (experience_id),
  experience_id VARCHAR(42) NOT NULL,
  experience_start_date VARCHAR(42),
  experience_end_date VARCHAR(42),
  experience_job_title VARCHAR(42),
  experience_description VARCHAR(42),
  entreprise_id VARCHAR(42) NOT NULL,
  candidate_id VARCHAR(42) NOT NULL
);

CREATE TABLE TOOL (
  PRIMARY KEY (tool_name),
  tool_name VARCHAR(42) NOT NULL,
  tool_icon VARCHAR(42)
);

CREATE TABLE Used_Skill (
  PRIMARY KEY (experience_id, competence_name),
  experience_id VARCHAR(42) NOT NULL,
  competence_name VARCHAR(42) NOT NULL
);

CREATE TABLE Used_Tool (
  PRIMARY KEY (experience_id, tool_name),
  experience_id VARCHAR(42) NOT NULL,
  tool_name VARCHAR(42) NOT NULL
);

ALTER TABLE DEGREE ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE Has_Applied ADD FOREIGN KEY (offer_id) REFERENCES JOB_OFFER (offer_id);
ALTER TABLE Has_Applied ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE Has_Certification ADD FOREIGN KEY (certification_name) REFERENCES CERTIFICATION (certification_name);
ALTER TABLE Has_Certification ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE Has_Faved ADD FOREIGN KEY (offer_id) REFERENCES JOB_OFFER (offer_id);
ALTER TABLE Has_Faved ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);

ALTER TABLE JOB_OFFER ADD FOREIGN KEY (entreprise_id) REFERENCES ENTREPRISE (entreprise_id);

ALTER TABLE PROFESSIONNAL_EXPERIENCE ADD FOREIGN KEY (candidate_id) REFERENCES CANDIDAT (candidate_id);
ALTER TABLE PROFESSIONNAL_EXPERIENCE ADD FOREIGN KEY (entreprise_id) REFERENCES ENTREPRISE (entreprise_id);

ALTER TABLE Used_Skill ADD FOREIGN KEY (competence_name) REFERENCES COMPETENCE (competence_name);
ALTER TABLE Used_Skill ADD FOREIGN KEY (experience_id) REFERENCES PROFESSIONNAL_EXPERIENCE (experience_id);

ALTER TABLE Used_Tool ADD FOREIGN KEY (tool_name) REFERENCES TOOL (tool_name);
ALTER TABLE Used_Tool ADD FOREIGN KEY (experience_id) REFERENCES PROFESSIONNAL_EXPERIENCE (experience_id);
